id: P008202
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4771
  title: བཟང་སྤྱོད་སྨོན་ལམ་གྱི་ཟིན་བྲིས་མཁན་ཆེན་འཇིགས་མེད་ཕུན་ཚོགས་ཀྱི་ཞལ་ལུང་།
  author: ''
  volumes:
    36f5d4af22cf4937aa5356b39d88778a:
      image_group_id: I3CN4773
      title: ''
      volume_number: 1
      total_pages: 202
      base_file: v001.txt
