id: I3611450A
legacy_id: P008202
ocr_import_info:
  bdrc_scan_id: W3CN4771
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T17:40:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:37:01.172474+00:00'
last_modified: 2022-09-03 22:37:09.142908
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4771
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4771
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཟང་སྤྱོད་སྨོན་ལམ་གྱི་ཟིན་བྲིས་མཁན་ཆེན་འཇིགས་མེད་ཕུན་ཚོགས་ཀྱི་ཞལ་ལུང་།
  author: མཁན་པོ་འཇིགས་ཕུན།
statistics:
  ocr_word_mean_confidence_index: 0.7145432961873786
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I3CN4773:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4773
      total_pages: 202
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4773.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.7145432961873786
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
